name: Build Sobonet APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source with Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Download Prebuilt LibXray AAR
        run: |
          mkdir -p V2rayNG/app/libs
          # دانلود مستقیم باینری هسته
          curl -L -f -o V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray.aar || \
          curl -L -f -o V2rayNG/app/libs/libv2ray.aar https://github.com/hiddify/AndroidLibXrayLite/releases/latest/download/libv2ray.aar

      - name: Build Native Hev Tunnel
        run: |
          if [ -f "./compile-hevton.sh" ]; then
            chmod +x ./compile-hevton.sh
            bash ./compile-hevton.sh
          fi

      - name: Build APK
        working-directory: ./V2rayNG
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: Upload SOBONET APK
        uses: actions/upload-artifact@v4
        with:
          name: SOBONET-Release-APK
          path: V2rayNG/app/build/outputs/apk/**/*.apk
          
